language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
  - nightly-2018-10-01-x86_64-unknown-linux-gnu\
env:
  - RUST_TEST_THREADS=1
script:
  - cargo build --verbose
  - cargo test --verbose -- --nocapture
  - cargo test --examples --- --nocapture

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
      rustup component add clippy-preview rustfmt;
      cargo fmt --all -- --check;
      cargo clippy -- -D clippy::all;
    fi

notifications:
  email:
    on_success: never
