[package]
name = "stdio-override"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["elichai2 <elichai.turkel@gmail.com>"]
repository = "https://github.com/elichai/stdio-override"
readme = "README.md"
edition = "2018"

[dependencies]
libc = "0.2"